// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPzXEdHI9mY8M8VIDI29cZvctktjsttzs',
    appId: '1:404251449019:web:b891ef15886898634c3b9e',
    messagingSenderId: '404251449019',
    projectId: 'car-dealer-79caa',
    authDomain: 'car-dealer-79caa.firebaseapp.com',
    storageBucket: 'car-dealer-79caa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLvOmhdCe125AW8ZuM5v2po_QSZ7v0Q3A',
    appId: '1:404251449019:android:1d831a2f0e32e6524c3b9e',
    messagingSenderId: '404251449019',
    projectId: 'car-dealer-79caa',
    storageBucket: 'car-dealer-79caa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-HZBLOILk1NhFb18jGIfJgG0mJlJTTpU',
    appId: '1:404251449019:ios:78960ad3153e8ce24c3b9e',
    messagingSenderId: '404251449019',
    projectId: 'car-dealer-79caa',
    storageBucket: 'car-dealer-79caa.appspot.com',
    iosBundleId: 'com.example.carAppBeta',
  );
}